from enum import Enum


class JumboCategory(Enum):
    FRUTAS_FRESCAS = "frutas-y-verduras-frescas/frutas-frescas.html"
    HORTALIZAS = "frutas-y-verduras-frescas/hortalizas.html"
    VIVERES = "frutas-y-verduras-frescas/viveres.html"
    CARNES = "carnes-pescados-y-mariscos/carnes.html"
    PESCADOS_Y_MARISCOS = "carnes-pescados-y-mariscos/pescados-y-mariscos.html"
    LACTEOS = "lacteos-y-huevos/lacteos.html"
    QUESOS = "lacteos-y-huevos/quesos.html"
    HUEVOS = "lacteos-y-huevos/huevos.html"
    JAMONES_COCIDOS_Y_CURADOS = "embutidos-y-charcuteria/jamones-cocidos-y-curados.html"
    SALAMI_COCIDO_Y_CURADO = "embutidos-y-charcuteria/salami-cocido-y-curado.html"
    MORTADELA = "embutidos-y-charcuteria/mortadela.html"
    SALCHICHAS = "embutidos-y-charcuteria/salchichas.html"
    TOCINETA = "embutidos-y-charcuteria/tocineta.html"
    PASTRAMI = "embutidos-y-charcuteria/pastrami.html"
    CHORIZOS_Y_MORCILLA = "embutidos-y-charcuteria/chorizos-y-morcilla.html"
    LONGANIZA = "embutidos-y-charcuteria/longaniza.html"
    FRUTAS_CONGELADAS = "congelados/frutas-congeladas.html"
    PAPAS_PRECOCIDAS = "congelados/papas-precocidas.html"
    VEGETALES_CONGELADOS = "congelados/vegetales-congelados.html"
    PASTAS_Y_MASAS_CONGELADAS = "congelados/pastas-y-masas-congeladas.html"
    REPOSTERIA_CONGELADA = "congelados/reposteria-congelada.html"
    PANADERIA_CONGELADA = "congelados/panaderia-congelada.html"
    JUGOS_CONCENTRADOS = "congelados/jugos-concentrados.html"
    PIZZAS_CONGELADAS = "congelados/pizzas-congeladas.html"
    PLATOS_PREPARADOS = "congelados/platos-preparados.html"
    APERITIVOS_Y_PICADERAS = "congelados/aperitivos-y-picaderas.html"
    AZUCAR_Y_SUSTITUTOS = "comestibles/azucar-y-sustitutos-azucar.html"
    DESAYUNO = "comestibles/desayuno.html"
    DULCES_Y_GALLETAS = "comestibles/dulces-y-galletas.html"
    CONDIMENTOS_Y_ESPECIAS = "comestibles/condimentos-y-especias.html"
    CONSERVAS_Y_ENCURTIDOS = "comestibles/conservas-y-encurtidos.html"
    ACEITES = "comestibles/aceites.html"
    ARROZ_Y_GRANOS_SECOS = "comestibles/arroz-y-granos-secos.html"
    HABICHUELAS = "comestibles/habichuelas.html"
    ADEREZOS_Y_SALSAS = "comestibles/aderezos-y-salsas.html"
    SOPAS = "comestibles/sopas.html"
    PASTAS_SECAS = "comestibles/pastas-secas.html"
    COMIDA_INTERNACIONAL = "comestibles/comida-internacional.html"
    PICADERAS = "comestibles/picaderas.html"
    INGREDIENTES_PANADERIA_Y_REPOSTERIA = (
        "comestibles/ingredientes-panaderia-y-reposteria.html"
    )
    PANADERIA_Y_REPOSTERIA = "comestibles/panaderia-y-reposteria.html"
    AGUA = "bebidas-no-alcoholicas/agua.html"
    JUGOS_Y_TE_FRIO = "bebidas-no-alcoholicas/jugos-y-te-frio.html"
    REFRESCOS = "bebidas-no-alcoholicas/refrescos.html"
    TONICA_Y_SODA = "bebidas-no-alcoholicas/tonica-y-soda.html"
    MALTAS = "bebidas-no-alcoholicas/maltas.html"
    BEBIDA_DEPORTIVA_Y_ENERGIZANTE = (
        "bebidas-no-alcoholicas/bebida-deportiva-y-energizantes.html"
    )
    VINO_SIN_ALCOHOL = "bebidas-no-alcoholicas/vinos-sin-alcohol.html"
    COCTELES_Y_MEZCLAS_PARA_COCTELES = (
        "bebidas-no-alcoholicas/cocteles-y-mezclas-para-cocteles.html"
    )
    CERVEZAS = "bebidas-alcoholicas/cervezas.html"
    VINO_TINTO = "bebidas-alcoholicas/vino-tinto.html"
    VINO_BLANCO_Y_ROSADO = "bebidas-alcoholicas/vino-blanco-y-rosado.html"
    ESPUMANTES_CAVAS_Y_SIDRAS = "bebidas-alcoholicas/espumantes-cavas-y-sidras.html"
    WHISKY = "bebidas-alcoholicas/whisky.html"
    VODKA_Y_GINEBRA = "bebidas-alcoholicas/vodka-y-ginebra.html"
    RON_Y_TEQUILA = "bebidas-alcoholicas/ron-y-tequila.html"
    PONCHES_Y_LICORES = "bebidas-alcoholicas/ponches-y-licores.html"
    SANGRIAS = "bebidas-alcoholicas/sangrias.html"
    CIGARRILLOS = "bebidas-alcoholicas/cigarrillos.html"
    ALIMENTACIÓN_BEBE = "bebe/alimentacion-bebe.html"
