from enum import Enum


class ProductCategory(Enum):
    CARNES = "Carnes"
    GRANOS = "Granos"
    EMBUTIDOS = "Embutidos"
    LACTEOS = "Lácteos"
    PAN = "Pan"
    VEGETALES = "Vegetales"
    CONGELADOS = "Congelados"
    DELI = "Deli"
    DESPENSA = "Despensa"
    GALLETAS_Y_DULCES = "Galletas y dulces"
    LISTOS_PARA_COMER = "Listos para comer"
    PANADERIA_Y_REPOSTERIA = "Panadería y repostería"
    PESCADOS_Y_MARISCOS = "Pescados y mariscos"
    ALIMENTOS_PARA_BEBE = "Alimentos para bebé"
    AGUAS = "Aguas"
    CERVEZAS = "Cervezas"
    HIDRATANTES = "Hidratantes"
    JUGOS = "Jugos"
    LICORES = "Licores"
    MALTAS = "Maltas"
    REFRESCOS_Y_ENERGITZANTES = "Refrescos y energizantes"
    SUPLEMENTOS_Y_PROTEINAS = "Suplementos y proteínas"
    VINOS_Y_ESPUMANTES = "Vinos y espumantes"
    CIGARRILLOS = "Cigarrillos"
    FRUTAS_CONGELADAS = "Frutas congeladas"
    FRUTAS_FRESCAS = "Frutas frescas"
    VEGETALES_CONGELADOS = "Vegetales congelados"
