from enum import Enum


class SirenaCategory(Enum):
    CARNES = "carnes"
    CONGELADOS = "congelados"
    DELI = "deli"
    DESPENSA = "despensa"
    GALLETAS_Y_DULCES = "galletas-y-dulces"
    LACTEOS_Y_HUEVOS = "lacteos-y-huevos"
    LISTOS_PARA_COMER = "listos-para-comer"
    PANADERIA_Y_REPOSTERIA = "panaderia-y-reposteria"
    PESCADOS_Y_MARISCOS = "pescados-y-mariscos"
    PICADERAS = "picaderas"
    ALIMENTOS_PARA_BEBE = "alimentos"
    AGUAS = "aguas"
    CERVEZAS = "cervezas"
    HIDRATANTES = "hidratantes"
    JUGOS = "jugos"
    LICORES = "licores"
    MALTAS = "maltas"
    REFRESCOS_Y_ENERGITZANTES = "refrescos-y-energizantes"
    SUPLEMENTOS_Y_PROTEINAS = "suplementos-y-proteinas"
    VINOS_Y_ESPUMANTES = "vinos-y-espumantes"
    CIGARRILLOS = "cigarrillos"
    FRUTAS_CONGELADAS = "frutas-congeladas"
    FRUTAS_FRESCAS = "frutas-frescas"
    VEGETALES_CONGELADOS = "vegetales-congelados"
    VEGETALES_FRESCOS = "vegetales-frescos"
